### ISSUE TITLE
Ошибки в работе

### ISSUE THREAD

**Issue by mars-1** [flicus/flibot#1]
Добрый вечер.

При запуске бота вываливаются ошибки вида:

`java -jar starter/build/libs/starter-0.9.0-all.jar
log4j:ERROR Could not read configuration file [log4j.properties].
java.io.FileNotFoundException: log4j.properties (Нет такого файла или каталога)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
        at org.schors.flibot.Main.main(Main.java:44)
log4j:ERROR Ignoring configuration file [log4j.properties].
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

Но это можно поправить (добавить путь etc/), но при любом запросе к боты выдаются ошибки:

`
сен 16, 2016 6:09:14 PM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage
java.lang.NullPointerException
        at org.schors.flibot.commands.FlibotCommand.getSearches(FlibotCommand.java:61)
        at org.schors.flibot.commands.DefaultCommand.execute(DefaultCommand.java:49)
        at org.schors.vertx.telegram.bot.commands.CommandManager.execute(CommandManager.java:59)
        at org.schors.flibot.FliBot.lambda$null$0(FliBot.java:114)
        at org.schors.flibot.DBServiceVertxEBProxy.lambda$isRegisterdUser$0(DBServiceVertxEBProxy.java:79)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$1(EventBusImpl.java:334)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:213)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:192)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)
`
`сен 16, 2016 6:09:14 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
        at org.schors.flibot.commands.FlibotCommand.getSearches(FlibotCommand.java:61)
        at org.schors.flibot.commands.DefaultCommand.execute(DefaultCommand.java:49)
        at org.schors.vertx.telegram.bot.commands.CommandManager.execute(CommandManager.java:59)
        at org.schors.flibot.FliBot.lambda$null$0(FliBot.java:114)
        at org.schors.flibot.DBServiceVertxEBProxy.lambda$isRegisterdUser$0(DBServiceVertxEBProxy.java:79)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$1(EventBusImpl.java:334)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:213)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:192)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)`

Система:
CentOS Linux release 7.2

**Comment by flicus** [comment]
пожалуйста, используйте пока ветку first, там стабильная версия, в хеде идет разработка, позже поменяю чтобы стабильная ветка была в хеде, а девелопмент в бранче

**Comment by flicus** [comment]
стабильная версия в master ветке
